// Asuka - VirtualDub Build/Post-Mortem Utility
//
// Copyright (C) 2005-2006 Avery Lee
// Copyright (C) 2024-2025 v0lt
//
// SPDX-License-Identifier: GPL-2.0-or-later
//

#include "stdafx.h"
#include <vd2/system/vdtypes.h>
#include <vd2/system/vdstl.h>
#include <vd2/system/filesys.h>
#include <string>
#include <vector>

#include "utils.h"

void tool_makearray(const vdfastvector<const wchar_t*>& args, const vdfastvector<const wchar_t*>& switches) {
	if (args.size() < 3) {
		printf("usage: makearray <binary file> <.cpp output file> <symbol name>\n");
		exit(5);
	}

	FILE *f = nullptr;
	errno_t err = _wfopen_s(&f, args[0], L"rb");
	if (err) {
		fail("    couldn't open: %ls\n", args[0]);
	}
	fseek(f, 0, SEEK_END);
	size_t l = ftell(f);
	vdfastvector<char> buf(l);
	fseek(f, 0, SEEK_SET);
	if (!buf.empty())
		fread(&buf[0], l, 1, f);
	fclose(f);

	f = nullptr;
	err = _wfopen_s(&f, args[1], L"w");
	if (err) {
		fail("    couldn't open: %ls\n", args[1]);
	}

	fprintf(f, "// Automatically generated by Asuka from \"%ls.\" DO NOT EDIT!\n\n", VDFileSplitPath(args[0]));

	fprintf(f, "extern const unsigned char %ls[]={\n", args[2]);

	for(size_t i=0; i<l; i += 32) {
		size_t limit = i+32;
		if (limit > l) {
			limit = l;
		}

		for (size_t j = i; j < limit; ++j) {
			fprintf(f, "0x%02x,", (uint8)buf[j]);
		}
		fputc('\n', f);
	}

	fprintf(f, "};\n");
	fclose(f);
}
